//
//  HighlightStyle.swift
//  Highlight
//
//  Created by Leon Li on 2020/10/12.
//

public enum HighlightStyle: String {
    case a11yDark = "a11y-dark"
    case a11yLight = "a11y-light"
    case agate = "agate"
    case anOldHope = "an-old-hope"
    case androidstudio = "androidstudio"
    case arduinoLight = "arduino-light"
    case arta = "arta"
    case ascetic = "ascetic"
    case atomOneDarkReasonable = "atom-one-dark-reasonable"
    case atomOneDark = "atom-one-dark"
    case atomOneLight = "atom-one-light"
    case brownPaper = "brown-paper"
    case brown = "brown-pap"
    case codepenEmbed = "codepen-embed"
    case colorBrewer = "color-brewer"
    case dark = "dark"
    case `default` = "default"
    case devibeans = "devibeans"
    case docco = "docco"
    case far = "far"
    case felipec = "felipec"
    case foundation = "foundation"
    case githubDarkDimmed = "github-dark-dimmed"
    case githubDark = "github-dark"
    case github = "github"
    case gml = "gml"
    case googlecode = "googlecode"
    case gradientDark = "gradient-dark"
    case gradientLight = "gradient-light"
    case grayscale = "grayscale"
    case hybrid = "hybrid"
    case idea = "idea"
    case intellijLight = "intellij-light"
    case irBlack = "ir-black"
    case isblEditorDark = "isbl-editor-dark"
    case isblEditorLight = "isbl-editor-light"
    case kimbieDark = "kimbie-dark"
    case kimbieLight = "kimbie-light"
    case lightfair = "lightfair"
    case lioshi = "lioshi"
    case magula = "magula"
    case monoBlue = "mono-blue"
    case monokaiSublime = "monokai-sublime"
    case monokai = "monokai"
    case nightOwl = "night-owl"
    case nnfxDark = "nnfx-dark"
    case nnfxLight = "nnfx-light"
    case nord = "nord"
    case obsidian = "obsidian"
    case pandaSyntaxDark = "panda-syntax-dark"
    case pandaSyntaxLight = "panda-syntax-light"
    case paraisoDark = "paraiso-dark"
    case paraisoLight = "paraiso-light"
    case pojoaque = "pojoaque"
    case purebasic = "purebasic"
    case qtcreatorDark = "qtcreator-dark"
    case qtcreatorLight = "qtcreator-light"
    case rainbow = "rainbow"
    case routeros = "routeros"
    case schoolBook = "school-book"
    case shadesOfPurple = "shades-of-purple"
    case srcery = "srcery"
    case stackoverflowDark = "stackoverflow-dark"
    case stackoverflowLight = "stackoverflow-light"
    case sunburst = "sunburst"
    case tokyoNightDark = "tokyo-night-dark"
    case tokyoNightLight = "tokyo-night-light"
    case tomorrowNightBlue = "tomorrow-night-blue"
    case tomorrowNightBright = "tomorrow-night-bright"
    case vs = "vs"
    case vs2015 = "vs2015"
    case xcode = "xcode"
    case xt256 = "xt256"
}
